### ISSUE TITLE
Error with UT Water Allocation Data Uploader: pass a table-valued parameter with 15 column(s) for user-defined table type requires 16 column(s).

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#93] opened 2020-11-17 17:08 UTC
Updating our WSWC input files to match the new schema updates.  Having an error pop up with the data loader I'm not familiar with.  Can you walk me through how I might fix this?

Using UT water allocation to test updates, and where I'm having issues: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Utah/WaterAllocation/ProcessedInputData/UTalloc

Error message is as follows: 

> System.Private.CoreLib: Exception while executing function: LoadSitesBatch. Core .Net SqlClient Data Provider: Trying to pass a table-valued parameter with 15 column(s) where the corresponding user-defined table type requires 16 column(s).

![image](https://user-images.githubusercontent.com/17555073/99422595-f2f46e00-28bc-11eb-89a3-aa8e166fe259.png)

**Comment by zlannin** [comment] 2020-11-17 21:04
@rwjam I noticed some discrepancies in columns names between the waterallocations.csv you mentioned and https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/develop/source/WesternStatesWater.WaDE.Accessors.Contracts.Import/WaterAllocation.cs the data loader uses. I was able to import the UTalloc files after fixing the discrepancies in watterallocations.csv. Could you please update the waterallocations.csv and re-run the data loader? Also we've merged code since you opened your issue which I believe is the cause of your reported issue.

**Comment by rwjam** [comment] 2020-11-17 23:02
@zlannin I updated the watterallocations.csv in the file to match that located at https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/develop/source/WesternStatesWater.WaDE.Accessors.Contracts.Import/WaterAllocation.cs the data loader use, but I'm still getting that same error.

**Comment by zlannin** [comment] 2020-11-24 16:09
This was resolved by getting latest changes and running db migrations.

**Closed by zlannin** 2020-11-24 16:09 UTC
Labels: bug
